### ISSUE TITLE
Endless Resends after End of Print (perhaps related to a misunderstood command?)

### ISSUE THREAD

**Issue by cakeller98** [foosel/OctoPrint#470]
commit: e7088ef06cde53cefe53bfc20f2a2abb4581c66a
on Windows 8.1 Tablet

Something is happening at the end of my prints that is causing the endless resend loop, until the connect button is pressed 2x.

The first press returns this error:

just messing arond at the terminal I found that any malformed command results in Octoprint thinking it's not connected 
The Disconnect turns to a Connect Button - though it has to be pressed 2x to actually reconnect as the first press will fail with the following error:
```
Changing monitoring state from 'Error: Format error
' to 'Closed'
Unexpected error while reading serial port: SerialException: 'Attempting to use a port that is not open' @ comm.py:_readline:986
Connection closed, closing down monitor
Changing monitoring state from 'Offline' to 'Opening serial port'
Connecting to: COM3
Unexpected error while connecting to serial port: COM3 SerialException: 'could not open port 'COM3': WindowsError(5, 'Access is denied.')' @ comm.py:_openSerial:949
Changing monitoring state from 'Opening serial port' to 'Error: Failed to open seria...'
```
After the second press of the connect button:
```
Changing monitoring state from 'Offline' to 'Opening serial port'
Connecting to: COM3
Connected to: Serial<id=0x23455d0, open=True>(port='COM3', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=2.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Recv: start
```
...etc and back to normal operation

I don't know what's happening at the end of a print that's causing this, or how long AFTER the print has finished this is occurring, however you can initiate this exact error behavior by submitting any malformed command into the terminal (e.g. simply send a single character like 'a' or a space.)

My repetier firmware commit (before customization): 2b1c85411069154b71d7aa580b4185837516d126
My octoprint is at commit: e7088ef06cde53cefe53bfc20f2a2abb4581c66a

**Comment by foosel** [comment]
Please test if this still occurs with current ``devel``

**Comment by scp38** [comment]
Sorry, but I was impatient and patched my Repetier firmware in May last year. I haven't seen the issue since then, so I can't say if the issue is resolved with your change mentioned above. 

What should this change do? Avoid flooding the firmware buffer with M105 temperature requests while waiting for the completion of a command that takes very long?

**Comment by foosel** [comment]
Among other things, yes.

**Comment by foosel** [comment]
Wrong button.

**Comment by foosel** [comment]
Closing since assuming this is now fixed by the extensive changes in the comm layer (no feedback, no choice)

**Comment by mrb255** [comment]
Sadly, I'm still getting this in 1.2.4. I first noticed it on an older version (whatever one that was bundled with my octopi image), then upgraded and it still reproduces. Oddly, I've never had a problem printing gcode produced by slic3r on octoprint (dozens of prints, no communication errors), only since I switched to cura for prime towers. Possibly also of note, the printer noticeably slows down and even stutters on curves when printing via octoprint, something that was much less pronounced before I switched from slic3r. It looks like the raspberry pi's cpu is pegged (version 1, b+).

I've tried to print the attached file 3 times and it always fails in about the same spot. It prints fine from the printer's sd card (Rostock max v2).

https://dl.dropboxusercontent.com/u/80114996/20140205_Marvin_KeyChain_Dual_Color_2_1_2.gcode
https://dl.dropboxusercontent.com/u/80114996/serial.log

**Comment by foosel** [comment]
Your serial log is truncated, the error might have started before the first line you provided or not, it's not possible to say from the excerpt. The starting point is of utmost importance however.

From what information *is* available, something fishy is definitely going on that looks like some off-by-one resend handling that started somewhere way up:

```
Send: N103256 G1 X15.161 Y6.676 E63.57619*91        // line N
Recv: ok 103256                                     // ok N
Send: N103257 G1 X15.288 Y7.368 E63.58917*91        // line N+1
Recv: Error:expected line 103257 got 103256         // got N but want N+1
Recv:                                               // empty line?!
Recv: Resend:103257                                 // resend N+1
Recv: ok                                            // that belongs to the resend
Send: N103257 G1 X15.288 Y7.368 E63.58917*91        // line N+1 again
Recv: ok 103257                                     // ok N+1
Send: N103258 G1 X14.767 Y7.413 E63.60218*85        // line N+2
Recv: Error:expected line 103258 got 103257         // got N+1, but want N+2
Recv:                                               // empty line?!
Recv: Resend:103258                                 // resend N+2
Recv: ok                                            // that belongs to the resend
Send: N103258 G1 X14.767 Y7.413 E63.60218*85        // line N+2 again
Recv: ok 103258                                     // ok N+2
```

What firmware that is? The ordering of the temperature output plus the line numbers on the `ok`s makes me think it's Repetier, which might be the clue here since I recently learnt from @repetier that Repetier will send resend requests for the same fault repeatedly to make sure they are not lost to communication errors - OctoPrint currently can't handle that (it reads a resend request as something definitive it always needs to respond to and never may ignore, since that is how it needs to be done for every other firmware but Repetier) and will need to be adjusted to do so. It might be that a superfluous resend by OctoPrint for one of these "repeats" caused everything to go out of sync here - the firmware only expected one reply to a resend it sent multiple times, but got multiple instead and then host and firmware started to continously misunderstand each other. But we can only be sure that is the reason by getting a full serial.log.

Another thing, regarding your problems with "stuttering", you didn't say if you explicitly enabled the serial logging for hunting down this issue or if you always have it enabled. If the latter, disable it (once we have tracked this issue down). Writing stuff to the file system is somewhat slow on the Pi, and doing that for every single line sent to and received from the firmware makes everything stutter, hence the big "warning" next to the serial log checkbox in the settings.

Considering that the whole communication layer has changed tremendously since that ticket here was created and hence any information in this ticket does not apply to the current code base any more, I'd also ask you to please [open a new bug ticket](https://github.com/foosel/OctoPrint/wiki/How-to-file-a-bug-report) for this. Please make sure to include all information asked of you.

**Comment by nophead** [comment]
Prints from Cura over USB stutter because it outputs very short segments if
the model contains them. Other slicers merge small segments to avoid comms
overload.

**Comment by foosel** [comment]
Not all prints sliced by Cura necessarily stutter over USB however, and worse than the small segments rendered by Cura is leaving the serial log enabled on a Pi1 while printing something semi complex. Hence the above hint ;)

**Comment by mrb255** [comment]
Hmm, I might have to reduce the stl's poly count then. But to answer your questions foosel, yes it is repetier (seemecnc's customized version 0.91, further customized by me for cyclops support). And yes, I do get the stuttering without serial logging a bit, but it is far far far worse with logging. Without logging, it just slows down a bit and sounds different. I'll open a new ticket when I have a full serial.log to post.

**Comment by foosel** [comment]
You might also want to try current devel, I added a new setting today that makes OctoPrint ignore repeated resend requests for the same line. I also could reproduce the exact behavior you got by faking repetiers resend behavior, so chances are high that problem is solved now too. I'll also add it to the upcoming 1.2.5 release.

**Comment by mrb255** [comment]
So repetier is the ie6 of the 3d printing world? :P
I reprinted that same gcode I posted and the devel branch, and it completed successfully. I did get the format error at one point (line 7953 of the attached log), but it looks like that resolved itself. Here's the copy I made of the serial log before it reset itself. I'll open a new bug if this crops up again.

https://dl.dropboxusercontent.com/u/80114996/serial_devel.log
